MAX_ATTEMPTS = 4
MAX_PREFERENCE_ASKS = 3

RATE_LIMIT_PER_SECOND = 5

MAX_DATE_DAYS_AHEAD = 365
# Local (America/Los_Angeles) hour after which a same-day hike request is
# considered too late to have enough daylight/time left.
SAME_DAY_CUTOFF_HOUR = 16

BAY_AREA_FALLBACK_LATLON = {"lat": 37.7749, "lon": -122.4194}

PREFERENCE_TOPICS = {
    "views": ["view", "views", "scenic", "waterfall", "ocean", "lake", "sunset"],
    "difficulty": ["easy", "moderate", "hard", "challenging", "beginner", "strenuous"],
    "elevation_gain": ["elevation", "gain", "climb", "steep", "vert"],
    "distance": ["mile", "miles", "km", "kilometer", "distance", "short", "long"],
}

PREFERENCE_TOPIC_LABELS = {
    "views": "the kind of views you want",
    "difficulty": "your preferred difficulty level",
    "elevation_gain": "your elevation gain preference",
    "distance": "your preferred total distance",
}

ALL_PREFERENCE_TOPICS = set(PREFERENCE_TOPICS)

NON_CA_STATE_NAMES = {
    "alabama",
    "alaska",
    "arizona",
    "arkansas",
    "colorado",
    "connecticut",
    "delaware",
    "florida",
    "georgia",
    "hawaii",
    "idaho",
    "illinois",
    "indiana",
    "iowa",
    "kansas",
    "kentucky",
    "louisiana",
    "maine",
    "maryland",
    "massachusetts",
    "michigan",
    "minnesota",
    "mississippi",
    "missouri",
    "montana",
    "nebraska",
    "nevada",
    "new hampshire",
    "new jersey",
    "new mexico",
    "new york",
    "north carolina",
    "north dakota",
    "ohio",
    "oklahoma",
    "oregon",
    "pennsylvania",
    "rhode island",
    "south carolina",
    "south dakota",
    "tennessee",
    "texas",
    "utah",
    "vermont",
    "virginia",
    "washington",
    "west virginia",
    "wisconsin",
    "wyoming",
    "district of columbia",
}

NON_CA_STATE_CODES = {
    "AL",
    "AK",
    "AZ",
    "AR",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "DC",
}

NON_US_COUNTRY_KEYWORDS = {
    "canada",
    "mexico",
    "united kingdom",
    "england",
    "france",
    "germany",
    "italy",
    "spain",
    "china",
    "japan",
    "india",
    "australia",
    "new zealand",
    "brazil",
    "argentina",
    "chile",
}
